import sipsMobileImage from "../assets/images/sips/sips.webp";
import develadWebImage from "../assets/images/develad/develad.webp";
import funlordMobileImage from "../assets/images/funlord/funlord.webp";
import funlordWebImage from "../assets/images/funlordweb/funlord-web.webp";
import aybumobileImage from "../assets/images/aybumobile/aybumobile.webp";
import finrendMobileImage from "../assets/images/finrend/finrend.webp";
import qrScanImage from "../assets/images/qrscan/qrscan.webp";
import omAppImage from "../assets/images/omapp/omapp.webp";
import playlandImage from "../assets/images/playland/playland.webp";
import openVoteImage from "../assets/images/openvote/openvote.webp";
import eservisImage from "../assets/images/eservis/eservis.webp";
import usecoImage from "../assets/images/useco/useco.webp";
import plndverseImage from "../assets/images/plndverse/plndverse.webp";
import ecourseImage from "../assets/images/ecourse/ecourse.webp";
import filminnImage from "../assets/images/filminn/filminn.webp";
import directAcademyImage from "../assets/images/directacademy/directAcademy.webp";
import galaksiOrganizationImage from "../assets/images/galaksiorganizasyon/galaksiOrganization.webp";
import monsterhuntImage from "../assets/images/monsterhunt/monsterhunt.webp";
import dailyfrontendImage from "../assets/images/dailyfrontend/dailyfrontend.webp";
import simongameImage from "../assets/images/simongame/simongame.webp";
import okkoImage from "../assets/images/okko/okko.webp";
import nodeapiImage from "../assets/images/nodeapi/nodeapi.webp";
//import pouchMobileImage from "../assets/images/pouchmobile/pouchmobile.png";
import navvigoMobileImage from "../assets/images/navvigomobile/navvigomobile.webp";
import navvigoWebImage from "../assets/images/navvigoweb/navvigoweb.webp";
import birF1TImage from "../assets/images/1f1t/1f1t.webp";
import tummiadImage from "../assets/images/tummiad/tummiad.webp";

//import emptyPhoto from "../assets/images/empty.png";

import eservisPhoto1 from "../assets/images/eservis/photo1.webp";
import eservisPhoto2 from "../assets/images/eservis/photo2.webp";
import funlordMobilePhoto1 from "../assets/images/funlord/photo1.webp";
import funlordMobilePhoto2 from "../assets/images/funlord/photo2.webp";
import funlordAdminPhoto1 from "../assets/images/funlordweb/photo1.webp";
import funlordAdminPhoto2 from "../assets/images/funlordweb/photo2.webp";
import aybuMobilePhoto1 from "../assets/images/aybumobile/photo1.webp";
import aybuMobilePhoto2 from "../assets/images/aybumobile/photo2.webp";
import qrScanPhoto1 from "../assets/images/qrscan/photo1.webp";
import qrScanPhoto2 from "../assets/images/qrscan/photo2.webp";
import omAppPhoto1 from "../assets/images/omapp/photo1.webp";
import omAppPhoto2 from "../assets/images/omapp/photo2.webp";
import finrendPhoto1 from "../assets/images/finrend/photo1.webp";
import finrendPhoto2 from "../assets/images/finrend/photo2.webp";
import playlandPhoto1 from "../assets/images/playland/photo1.webp";
import playlandPhoto2 from "../assets/images/playland/photo2.webp";
import openvotePhoto1 from "../assets/images/openvote/photo1.webp";
import openvotePhoto2 from "../assets/images/openvote/photo2.webp";
import usecoPhoto1 from "../assets/images/useco/photo1.webp";
import usecoPhoto2 from "../assets/images/useco/photo2.webp";
import ecoursePhoto1 from "../assets/images/ecourse/photo1.webp";
import ecoursePhoto2 from "../assets/images/ecourse/photo2.webp";
import plndversePhoto1 from "../assets/images/plndverse/photo1.webp";
import plndversePhoto2 from "../assets/images/plndverse/photo2.webp";
import filminnPhoto1 from "../assets/images/filminn/photo1.webp";
import filminnPhoto2 from "../assets/images/filminn/photo2.webp";
import directacademyPhoto1 from "../assets/images/directacademy/photo1.webp";
import directacademyPhoto2 from "../assets/images/directacademy/photo2.webp";
import galaksiorganizasyonPhoto1 from "../assets/images/galaksiorganizasyon/photo1.webp";
import galaksiorganizasyonPhoto2 from "../assets/images/galaksiorganizasyon/photo2.webp";
import monsterhuntPhoto1 from "../assets/images/monsterhunt/photo1.webp";
import monsterhuntPhoto2 from "../assets/images/monsterhunt/photo2.webp";
import dailyfrontendPhoto1 from "../assets/images/dailyfrontend/photo1.webp";
import dailyfrontendPhoto2 from "../assets/images/dailyfrontend/photo2.webp";
import simongamePhoto1 from "../assets/images/simongame/photo1.webp";
import simongamePhoto2 from "../assets/images/simongame/photo2.webp";
import okkoPhoto1 from "../assets/images/okko/photo1.webp";
import okkoPhoto2 from "../assets/images/okko/photo2.webp";
import nodeapiPhoto1 from "../assets/images/nodeapi/photo1.webp";
import nodeapiPhoto2 from "../assets/images/nodeapi/photo2.webp";
//import pouchMobilePhoto from "../assets/images/pouchmobile/photo1.png";
import navvigoMobilePhoto from "../assets/images/navvigomobile/photo1.webp";
import navvigoWebPhoto from "../assets/images/navvigoweb/photo1.webp";
import birF1TPhoto from "../assets/images/1f1t/photo1.webp";
import tummiadPhoto from "../assets/images/tummiad/photo1.webp";
import sipsPhoto1 from "../assets/images/sips/photo1.webp";
import sipsPhoto2 from "../assets/images/sips/photo2.webp";
import sipsPhoto3 from "../assets/images/sips/photo3.webp";
import sipsPhoto4 from "../assets/images/sips/photo4.webp";
import sipsPhoto5 from "../assets/images/sips/photo5.webp";
import sipsPhoto6 from "../assets/images/sips/photo6.webp";
import sipsPhoto7 from "../assets/images/sips/photo7.webp";
import develadPhoto1 from "../assets/images/develad/photo1.webp";
import develadPhoto2 from "../assets/images/develad/photo2.webp";

import storifyImage from "../assets/images/storify/storify.webp";
import storifyPhoto1 from "../assets/images/storify/photo1.webp";
import storifyPhoto2 from "../assets/images/storify/photo2.webp";
import storifyPhoto3 from "../assets/images/storify/photo3.webp";

import flowaiImage from "../assets/images/flowai/flowai.webp";
import flowaiPhoto1 from "../assets/images/flowai/photo1.webp";
import flowaiPhoto2 from "../assets/images/flowai/photo2.webp";
import flowaiPhoto3 from "../assets/images/flowai/photo3.webp";

import finrendstakeImage from "../assets/images/finrendstake/finrendstake.webp";
import finrendstakePhoto1 from "../assets/images/finrendstake/photo1.webp";
import finrendstakePhoto2 from "../assets/images/finrendstake/photo2.webp";

import cakirlojistikImage from "../assets/images/cakirlojistik/cakirlojistik.webp";
import cakirlojistikPhoto1 from "../assets/images/cakirlojistik/photo1.webp";
import cakirlojistikPhoto2 from "../assets/images/cakirlojistik/photo2.webp";
import cakirlojistikPhoto3 from "../assets/images/cakirlojistik/photo3.webp";
import cakirlojistikPhoto4 from "../assets/images/cakirlojistik/photo4.webp";
import cakirlojistikPhoto5 from "../assets/images/cakirlojistik/photo5.webp";
import cakirlojistikPhoto6 from "../assets/images/cakirlojistik/photo6.webp";
import cakirlojistikPhoto7 from "../assets/images/cakirlojistik/photo7.webp";
import cakirlojistikPhoto8 from "../assets/images/cakirlojistik/photo8.webp";
import cakirlojistikPhoto9 from "../assets/images/cakirlojistik/photo9.webp";

import tonminterImage from "../assets/images/tonminter/tonminter.webp";
import tonminterPhoto1 from "../assets/images/tonminter/photo1.webp";
import tonminterPhoto2 from "../assets/images/tonminter/photo2.webp";

import tonutilsImage from "../assets/images/tonutils/tonutils.webp";
import tonutilsPhoto1 from "../assets/images/tonutils/photo1.webp";
import tonutilsPhoto2 from "../assets/images/tonutils/photo2.webp";
import tonutilsPhoto3 from "../assets/images/tonutils/photo3.webp";

import vulnheroImage from "../assets/images/vulnhero/vulnhero.webp";
import vulnheroPhoto1 from "../assets/images/vulnhero/photo1.webp";
import vulnheroPhoto2 from "../assets/images/vulnhero/photo2.webp";
import vulnheroPhoto3 from "../assets/images/vulnhero/photo3.webp";

import weatherImage from "../assets/images/weather/weather.webp";
import weatherPhoto1 from "../assets/images/weather/photo1.webp";
import weatherPhoto2 from "../assets/images/weather/photo2.webp";
import weatherPhoto3 from "../assets/images/weather/photo3.webp";
import weatherPhoto4 from "../assets/images/weather/photo4.webp";
import weatherPhoto5 from "../assets/images/weather/photo5.webp";


export const selectedWorks = [
  {
    image: weatherImage,
    title: "Weather",
    description: "A weather app that shows the weather of the city.",
    tags: ["React", "CesiumJS", "Java Spring Boot", "PostgreSQL", "OpenWeatherMap"],
    playStore: "",
    appStore: "",
    webLink: "https://weather-cesium.vercel.app/",
    githubLink: "",
    generalLink: "/work/weather",
    type: "web",
    type2: "backend",
  },
  {
    image: vulnheroImage,
    title: "VulnHero",
    description: "A modern landing page for VulnHero's web security platform.",
    tags: ["React", "NextJS", "TailwindCSS", "NodeJS", "Express", "MongoDB", "Parse"],
    playStore: "",
    appStore: "",
    webLink: "https://vulnhero.com/",
    githubLink: "",
    generalLink: "/work/vulnhero",
    type: "web",
    type2: "backend",
  },
  {
    image: tonutilsImage,
    title: "Ton Utils",
    description: "Ton Utils is a collection of tools for the TON blockchain.",
    tags: ["VueJS", "NuxtJS", "FunC", "TonApi", "Blockchain", "Docker", "GraphQL", "Prisma"],
    playStore: "",
    appStore: "",
    webLink: "https://tonutils.nuxt.dev/",
    githubLink: "https://github.com/clickerspace/vesting",
    generalLink: "/work/tonutils",
    type: "web",
    type2: "blockchain",
  },
  {
    image: tonminterImage,
    title: "Ton Minter",
    description: "Ton Minter is a platform that allows users to mint jettons on the TON blockchain.",
    tags: ["React", "FunC", "TonApi", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "https://tonminter.co/",
    githubLink: "https://github.com/mertcankose/tonminter-contracts",
    generalLink: "/work/tonminter",
    type: "web",
    type2: "blockchain",
  },
  {
    image: flowaiImage,
    title: "FlowAI",
    description: "Transform your ideas into professionally crafted rap songs using AI technology.",
    tags: ["React Native", "NodeJS", "Express", "MongoDB", "Music API"],
    playStore: "",
    appStore: "https://apps.apple.com/us/app/ai-rap-music-generator-flow-ai/id6740488650",
    webLink: "https://flowai-web.vercel.app/",
    githubLink: "",
    generalLink: "/work/flowai",
    type: "mobile",
    type2: "backend",
  },
  {
    image: storifyImage,
    title: "Storify",
    description: "Discover a world of calming bedtime stories and customizable sleep sounds.",
    tags: ["React Native", "Supabase", "ElevenLabs API", "Firebase"],
    playStore: "https://play.google.com/store/apps/details?id=com.kosemertcan.storify",
    appStore: "https://apps.apple.com/us/app/storify/id6739540392",
    webLink: "https://storifyapp.vercel.app/",
    githubLink: "",
    generalLink: "/work/storify",
    type: "mobile",
    type2: "",
  },
  {
    image: cakirlojistikImage,
    title: "Çakır Lojistik",
    description: "Cakirlojistik is a company that provides logistics services.",
    tags: ["React", "TailwindCSS", "Google Maps API", "Shadcn UI", "Python", "FastAPI"],
    playStore: "https://play.google.com/store/apps/details?id=com.rafintech.cakirlojistik",
    appStore: "",
    webLink: "https://cakir-frontend.pages.dev/",
    githubLink: "",
    generalLink: "/work/cakirlojistik",
    type: "web",
    type2: "mobile",
  },
  {
    image: finrendstakeImage,
    title: "Finrend Stake",
    description: "Stake your Finrend tokens and earn rewards.",
    tags: ["React", "TailwindCSS", "Solidity"],
    playStore: "",
    appStore: "",
    webLink: "https://stake.finrend.com/",
    githubLink: "",
    generalLink: "/work/finrendstake",
    type: "web",
    type2: "blockchain",
  },
  {
    image: sipsMobileImage,
    title: "Sips",
    description: "An app that combines the dating and coffee experience.",
    tags: ["React Native", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/sips",
    type: "mobile",
    type2: "",
  },
  {
    image: develadWebImage,
    title: "Develad",
    description: "A website promoting the AR/VR product and a blockchain-based pre-sale page for DVL token.",
    tags: ["React", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "https://dvltoken.com/",
    githubLink: "",
    generalLink: "/work/develad",
    type: "web",
    type2: "blockchain",
  },
  /*
  {
    image: pouchMobileImage,
    title: "Pouch Wallet",
    description:
      "A crypto wallet unlike any other, seamless portfolio management",
    tags: ["React Native", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/pouch-wallet",
    type: "mobile",
  },
  */
  {
    image: navvigoMobileImage,
    title: "Navvigo",
    description:
      "Decentralized navigation app that designed socio-economically to change people's traveling habits by its special rewarding system.",
    tags: ["React Native", "Blockchain", "Solidity", "Web3", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/navvigo-mobile",
    type: "mobile",
    type2: "blockchain",
  },
  {
    image: funlordMobileImage,
    title: "Funlord Mobil",
    description:
      "Qr payment solution to play with toys in certain entertainment centers. It hosts the campaigns of entertainment brands. It includes Iyzico payment system.",
    tags: ["React Native", "Iyzico Payment", "Python", "Django", "PostgreSQL"],
    playStore: "https://play.google.com/store/apps/details?id=com.funlord",
    appStore: "https://apps.apple.com/tr/app/funlord-mobil/id6446031864?l=tr",
    webLink: "",
    githubLink: "",
    generalLink: "/work/funlord-mobile",
    type: "mobile",
    type2: "backend",
  },
  {
    image: okkoImage,
    title: "Okko",
    description:
      "Okko is an entertainment company with adventure parks and various other entertainment centers. I developed a ticket buying application for this company. The idea is that there is no queue at the box office and people can buy tickets easily.",
    tags: ["React", "Vite", "TailwindCSS", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "https://bilet.okko.com.tr/",
    githubLink: "",
    generalLink: "/work/okko",
    type: "web",
    type2: "",
  },
  {
    image: aybumobileImage,
    title: "Aybu Mobile",
    description:
      "The application that contains the food menu, socialization section and announcements for our university.",
    tags: ["React Native", "Reanimated"],
    playStore: "https://play.google.com/store/apps/details?id=com.aybumobile&gl=TR",
    appStore: "https://apps.apple.com/tr/app/ayb%C3%BC-mobile/id1658659307?l=tr",
    webLink: "https://aybumobile.com",
    githubLink: "https://github.com/thesammet/aybumobile",
    generalLink: "/work/aybu-mobile",
    type: "mobile",
    type2: "",
  },

  {
    name: "finrend",
    image: finrendMobileImage,
    title: "Finrend",
    description:
      "Finrend is a financial application taht followed signals from the stock market and gave recommendations to users.",
    tags: ["React Native"],
    playStore: "https://play.google.com/store/apps/details?id=com.finrend",
    appStore: "https://apps.apple.com/gw/app/finrend-your-financial-friend/id1633138818",
    webLink: "http://finrend.com/",
    githubLink: "",
    generalLink: "/work/finrend",
    type: "mobile",
    type2: "",
  },
  {
    image: omAppImage,
    title: "OmApp",
    description:
      "A crypto app. It is a super app where crypto wallets and users can track their assets and receive notifications.",
    tags: ["React Native", "Web3", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/omapp",
    type: "mobile",
    type2: "blockchain",
  },
  {
    name: "navvigoweb",
    image: navvigoWebImage,
    title: "Navvigo Web",
    description: "Official website of the Navvigo project.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://navvigo.com/",
    githubLink: "",
    generalLink: "/work/navvigo-web",
    type: "web",
    type2: "",
  },
  {
    name: "tummiad",
    image: tummiadImage,
    title: "Tümmiad",
    description: "Tüm Mucitler İcat-İnovasyon ve Araştırma Derneğimi Resmi Web Sitesi",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://tummiad.org.tr/",
    githubLink: "",
    generalLink: "/work/tummiad",
    type: "web",
    type2: "",
  },
  {
    name: "1f1t",
    image: birF1TImage,
    title: "Bir Fikir Bir Türkiye",
    description: "1 Fikir 1 Türkiye Organizasyonunun Resmi Websitesi",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://1fikir1turkiye.com/",
    githubLink: "",
    generalLink: "/work/1f1t",
    type: "web",
    type2: "",
  },
  {
    name: "open-vote",
    image: openVoteImage,
    title: "Open Vote",
    description:
      "I have developed a mobile application of a blockchain-based service with react native for the company I work for. I have used web3 libraries such as Wallet Connect.",
    tags: ["React Native", "Web3", "Blockchain"],
    playStore: "https://play.google.com/store/apps/details?id=com.om.openvote&hl=tr&gl=US",
    appStore: "https://apps.apple.com/gb/app/open-vote/id1601587507",
    webLink: "",
    githubLink: "",
    generalLink: "/work/open-vote",
    type: "mobile",
    type2: "blockchain",
  },
  {
    name: "playland",
    image: playlandImage,
    title: "Playland",
    description:
      "Playland is a project that I am involved in as a freelancer. QR Supported payment system (iyzico) for a company that already has entertainment stores in most provinces of Turkey, is a multi-featured mobile application where parents can follow their children in the game.",
    tags: ["React Native", "Iyzico Payment"],
    playStore: "https://play.google.com/store/apps/details?id=com.playlandmobile&hl=tr&gl=US",
    appStore: "https://apps.apple.com/tr/app/playland-mobil/id1631854531",
    webLink: "",
    githubLink: "",
    generalLink: "/work/playland",
    type: "mobile",
    type2: "",
  },
  {
    image: qrScanImage,
    title: "QR Scan",
    description:
      "An application that allows a user to extract text from a photo and save it in an excel file on his phone.",
    tags: ["React Native", "SQLite", "AWS"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "https://github.com/mertcankose/qrscan",
    generalLink: "/work/qr-scan",
    type: "mobile",
    type2: "",
  },

  {
    image: eservisImage,
    title: "E-Servis",
    description:
      "A platform where parents can monitor their children on the school bus along the way, and school management and service companies can easily control and manage the bus.",
    tags: ["React", "Vite", "TailwindCSS", "Google Map"],
    playStore: "https://play.google.com/store/apps/details?id=com.vyros.eservis&pli=1",
    appStore: "https://apps.apple.com/tr/app/eservis/id6463719378",
    webLink: "https://panel.eservis.app/",
    githubLink: "",
    generalLink: "/work/e-servis",
    type: "web",
    type2: "",
  },
  {
    image: funlordWebImage,
    title: "Funlord Admin Panel",
    description:
      "Admin panel of Funlord Mobile application. It was developed in addition to the application for super admin and staff. They can manage the campaigns, toys, and users.",
    tags: ["React", "Vite", "TailwindCSS", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "https://www.funlord.com.tr/",
    githubLink: "",
    generalLink: "/work/funlord-admin",
    type: "web",
    type2: "backend",
  },
  {
    image: nodeapiImage,
    title: "Backend Service (NodeJS)",
    description:
      "An asana clone-like API project I created with Node js and Express. I created my service by following Layered Architecture.",
    tags: ["NodeJS", "Express", "MongoDB"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "https://github.com/mertcankose/node-application",
    generalLink: "/work/node-api",
    type: "backend",
    type2: "",
  },
  {
    name: "useco",
    image: usecoImage,
    title: "Useco",
    description: "A landing page of an event mobile application.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://useco.net/",
    githubLink: "",
    generalLink: "/work/useco",
    type: "web",
    type2: "",
  },
  {
    name: "plndverse",
    image: plndverseImage,
    title: "Playland Verse",
    description: "A landing page of an playland verse brand.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://www.plndverse.com/",
    githubLink: "",
    generalLink: "/work/plndverse",
    type: "web",
    type2: "",
  },
  {
    name: "e-course",
    image: ecourseImage,
    title: "E-Course",
    description: "E-Course is a example dashboard of a e-learning platform.",
    tags: ["Vue", "Vuex", "Firebase"],
    playStore: "",
    appStore: "",
    webLink: "https://e-course-dashboard.vercel.app/",
    githubLink: "",
    generalLink: "/work/e-course",
    type: "web",
    type2: "",
  },
  {
    name: "filminn",
    image: filminnImage,
    title: "Filminn",
    description: "Filminn is a landing page of a movie platform.",
    tags: ["HTML", "CSS", "Gulp.js"],
    playStore: "",
    appStore: "",
    webLink: "https://filminn.vercel.app/",
    githubLink: "",
    generalLink: "/work/filminn",
    type: "web",
    type2: "",
  },
  {
    name: "direct-academy",
    image: directAcademyImage,
    title: "Direct Academy",
    description: "Dental education presentation website.",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://directacademy.net/",
    githubLink: "",
    generalLink: "/work/direct-academy",
    type: "web",
    type2: "",
  },
  {
    name: "galaksi-organization",
    image: galaksiOrganizationImage,
    title: "Galaksi Organization",
    description: "An organization website that presents the organization tools.",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://galaksiorganizasyon.com/",
    githubLink: "",
    generalLink: "/work/galaksi-organization",
    type: "web",
    type2: "",
  },
];

export const allWorks = [
  {
    name: "weather",
    image: weatherImage,
    title: "Weather",
    description: "A weather app that shows the weather of the city.",
    tags: ["React", "CesiumJS", "Java Spring Boot", "PostgreSQL", "OpenWeatherMap"],
    playStore: "",
    appStore: "",
    webLink: "https://weather-cesium.vercel.app/",
    githubLink: "",
    generalLink: "/work/weather",
    photo1: weatherPhoto1,
    photo2: weatherPhoto2,
    photo3: weatherPhoto3,
    photo4: weatherPhoto4,
    photo5: weatherPhoto5,
    text: "",
    type: "web",
    type2: "backend",
  },
  {
    name: "vulnhero",
    image: vulnheroImage,
    title: "VulnHero",
    description: "A modern landing page for VulnHero's web security platform.",
    tags: ["React", "NextJS", "TailwindCSS", "NodeJS", "Express", "MongoDB", "Parse"],
    playStore: "",
    appStore: "",
    webLink: "https://vulnhero.com/",
    githubLink: "",
    generalLink: "/work/vulnhero",
    photo1: vulnheroPhoto1,
    photo2: vulnheroPhoto2,
    photo3: vulnheroPhoto3,
    text: "",
    type: "web",
    type2: "backend",
  },
  {
    name: "tonutils",
    image: tonutilsImage,
    title: "Ton Utils",
    description: "Ton Utils is a collection of tools for the TON blockchain.",
    tags: ["VueJS", "NuxtJS", "FunC", "TonApi", "Blockchain", "Docker", "GraphQL", "Prisma"],
    playStore: "",
    appStore: "",
    webLink: "https://tonutils.nuxt.dev/",
    githubLink: "https://github.com/clickerspace/vesting",
    generalLink: "/work/tonutils",
    photo1: tonutilsPhoto1,
    photo2: tonutilsPhoto2,
    photo3: tonutilsPhoto3,
    text: "",
    type: "web",
    type2: "blockchain",
  },
  {
    name: "tonminter",
    image: tonminterImage,
    title: "Ton Minter",
    description: "Ton Minter is a platform that allows users to mint jettons on the TON blockchain.",
    tags: ["React", "FunC", "TonApi", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "https://tonminter.co/",
    githubLink: "https://github.com/mertcankose/tonminter-contracts",
    generalLink: "/work/tonminter",
    photo1: tonminterPhoto1,
    photo2: tonminterPhoto2,
    text: "",
    type: "web",
    type2: "blockchain",
  },
  {
    name: "flowai",
    image: flowaiImage,
    title: "FlowAI",
    description: "Transform your ideas into professionally crafted rap songs using AI technology.",
    tags: ["React Native", "NodeJS", "Express", "MongoDB", "Music API"],
    playStore: "",
    appStore: "https://apps.apple.com/us/app/ai-rap-music-generator-flow-ai/id6740488650",
    webLink: "https://flowai-web.vercel.app/",
    githubLink: "",
    generalLink: "/work/flowai",
    photo1: flowaiPhoto1,
    photo2: flowaiPhoto2,
    photo3: flowaiPhoto3,
    text: "",
    type: "mobile",
    type2: "backend",
  },
  {
    name: "storify",
    image: storifyImage,
    title: "Storify",
    description: "Discover a world of calming bedtime stories and customizable sleep sounds.",
    tags: ["React Native", "Supabase", "ElevenLabs API", "Firebae"],
    playStore: "https://play.google.com/store/apps/details?id=com.kosemertcan.storify",
    appStore: "https://apps.apple.com/us/app/storify/id6739540392",
    webLink: "https://storifyapp.vercel.app/",
    githubLink: "",
    generalLink: "/work/storify",
    photo1: storifyPhoto1,
    photo2: storifyPhoto2,
    photo3: storifyPhoto3,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "cakirlojistik",
    image: cakirlojistikImage,
    title: "Çakır Lojistik",
    description: "Cakirlojistik is a company that provides logistics services.",
    tags: ["React", "TailwindCSS", "Google Maps API", "Shadcn UI", "Python", "FastAPI"],
    playStore: "https://play.google.com/store/apps/details?id=com.rafintech.cakirlojistik",
    appStore: "",
    webLink: "https://cakir-frontend.pages.dev/",
    githubLink: "",
    generalLink: "/work/cakirlojistik",
    photo1: cakirlojistikPhoto1,
    photo2: cakirlojistikPhoto2,
    photo3: cakirlojistikPhoto3,
    photo4: cakirlojistikPhoto4,
    photo5: cakirlojistikPhoto5,
    photo6: cakirlojistikPhoto6,
    photo7: cakirlojistikPhoto7,
    photo8: cakirlojistikPhoto8,
    photo9: cakirlojistikPhoto9,
    text: "",
    type: "web",
    type2: "mobile",
  },
  {
    name: "finrendstake",
    image: finrendstakeImage,
    title: "Finrend Stake",
    description: "Stake your Finrend tokens and earn rewards.",
    tags: ["React", "TailwindCSS", "Solidity"],
    playStore: "",
    appStore: "",
    webLink: "https://stake.finrend.com/",
    githubLink: "",
    generalLink: "/work/finrendstake",
    photo1: finrendstakePhoto1,
    photo2: finrendstakePhoto2,
    text: "",
    type: "web",
    type2: "blockchain",
  },
  {
    name: "sips",
    image: sipsMobileImage,
    title: "Sips",
    description: "An app that combines the dating and coffee experience.",
    tags: ["React Native", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/sips",
    photo1: sipsPhoto1,
    photo2: sipsPhoto2,
    photo3: sipsPhoto3,
    photo4: sipsPhoto4,
    photo5: sipsPhoto5,
    photo6: sipsPhoto6,
    photo7: sipsPhoto7,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "develad",
    image: develadWebImage,
    title: "Develad",
    description: "A website promoting the AR/VR product and a blockchain-based pre-sale page for DVL token.",
    tags: ["React", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "https://dvltoken.com/",
    githubLink: "",
    generalLink: "/work/develad",
    photo1: develadPhoto1,
    photo2: develadPhoto2,
    text: "",
    type: "web",
    type2: "blockchain",
  },
  /*
  {
    name: "pouch-wallet",
    image: pouchMobileImage,
    title: "Pouch Wallet",
    description:
      "A crypto wallet unlike any other, seamless portfolio management.",
    tags: ["React Native", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/funlord-mobile",
    photo1: pouchMobilePhoto,
    photo2: pouchMobilePhoto,
    text: "",
    type: "mobile",
  },
  */
  {
    name: "navvigo-mobile",
    image: navvigoMobileImage,
    title: "Navvigo",
    description:
      "Decentralized navigation app that designed socio-economically to change people's traveling habits by its special rewarding system.",
    tags: ["React Native", "Blockchain", "Solidity", "Web3", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/navvigo-mobile",
    photo1: navvigoMobilePhoto,
    photo2: navvigoMobilePhoto,
    text: "",
    type: "mobile",
    type2: "blockchain",
  },

  {
    name: "funlord-mobile",
    image: funlordMobileImage,
    title: "Funlord Mobil",
    description:
      "Funlord offers a qr payment solution to play with toys in certain entertainment centers and is a mobile application that hosts the campaigns of entertainment brands. I made the whole app with React Native.",
    tags: ["React Native", "Iyzico Payment", "Python", "Django", "PostgreSQL"],
    playStore: "https://play.google.com/store/apps/details?id=com.funlord",
    appStore: "https://apps.apple.com/tr/app/funlord-mobil/id6446031864?l=tr",
    webLink: "",
    githubLink: "",
    generalLink: "/work/funlord-mobile",
    photo1: funlordMobilePhoto1,
    photo2: funlordMobilePhoto2,
    text: "",
    type: "mobile",
    type2: "backend",
  },
  {
    name: "aybu-mobile",
    image: aybumobileImage,
    title: "Aybu Mobile",
    description:
      "The mobile application we developed for our university. The application consists of a weekly menu, monthly food trends, access to school announcements and Aybü Social, the most exciting part of the application. Thus, it makes it easier for students to acquire knowledge and socialize.",
    tags: ["React Native", "Reanimated"],
    playStore: "https://play.google.com/store/apps/details?id=com.aybumobile&gl=TR",
    appStore: "https://apps.apple.com/tr/app/ayb%C3%BC-mobile/id1658659307?l=tr",
    webLink: "https://aybumobile.com",
    githubLink: "https://github.com/thesammet/aybumobile",
    generalLink: "/work/aybu-mobile",
    photo1: aybuMobilePhoto1,
    photo2: aybuMobilePhoto2,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "finrend",
    image: finrendMobileImage,
    title: "Finrend",
    description:
      "Finrend is a financial application taht followed signals from the stock market and gave recommendations to users.",
    tags: ["React Native"],
    playStore: "https://play.google.com/store/apps/details?id=com.finrend",
    appStore: "https://apps.apple.com/gw/app/finrend-your-financial-friend/id1633138818",
    webLink: "http://finrend.com/",
    githubLink: "",
    generalLink: "/work/finrend",
    photo1: finrendPhoto1,
    photo2: finrendPhoto2,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "omapp",
    image: omAppImage,
    title: "OmApp",
    description:
      "I have developed the front side of a crypto wallet with react native for the company I work for. I used web3 libraries to create wallets and transfer assets. I have significantly shortened the wallet creation time using hdwallet. We got the project out very quickly with a quick grasp of a new technology like Web3.",
    tags: ["React Native", "Web3", "Blockchain"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "",
    generalLink: "/work/omapp",
    photo1: omAppPhoto1,
    photo2: omAppPhoto2,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "navvigo-web",
    image: navvigoWebImage,
    title: "Navvigo Web",
    description: "Official website of the Navvigo project.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://navvigo.com/",
    githubLink: "",
    generalLink: "/work/navvigo-web",
    photo1: navvigoWebPhoto,
    photo2: navvigoWebPhoto,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "tummiad",
    image: tummiadImage,
    title: "Tümmiad",
    description: "Tüm Mucitler İcat-İnovasyon ve Araştırma Derneğimi Resmi Web Sitesi",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://tummiad.org.tr/",
    githubLink: "",
    generalLink: "/work/tummiad",
    photo1: tummiadPhoto,
    photo2: tummiadPhoto,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "1f1t",
    image: birF1TImage,
    title: "1 Fikir 1 Türkiye",
    description: "1 Fikir 1 Türkiye Organizasyonunun Resmi Websitesi",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://1fikir1turkiye.com/",
    githubLink: "",
    generalLink: "/work/1f1t",
    photo1: birF1TPhoto,
    photo2: birF1TPhoto,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "open-vote",
    image: openVoteImage,
    title: "Open Vote",
    description:
      "I have developed a mobile application of a blockchain-based service with react native for the company I work for. I have used web3 libraries such as Wallet Connect.",
    tags: ["React Native", "Web3", "Blockchain"],
    playStore: "https://play.google.com/store/apps/details?id=com.om.openvote&hl=tr&gl=US",
    appStore: "https://apps.apple.com/gb/app/open-vote/id1601587507",
    webLink: "",
    githubLink: "",
    generalLink: "/work/open-vote",
    photo1: openvotePhoto1,
    photo2: openvotePhoto2,
    text: "",
    type: "mobile",
    type2: "blockchain",
  },
  {
    name: "playland",
    image: playlandImage,
    title: "Playland",
    description:
      "Playland is a project that I am involved in as a freelancer. QR Supported payment system (iyzico) for a company that already has entertainment stores in most provinces of Turkey, is a multi-featured mobile application where parents can follow their children in the game.",
    tags: ["React Native", "Iyzico Payment"],
    playStore: "https://play.google.com/store/apps/details?id=com.playlandmobile&hl=tr&gl=US",
    appStore: "https://apps.apple.com/tr/app/playland-mobil/id1631854531",
    webLink: "plndverse.com",
    githubLink: "",
    generalLink: "/work/playland",
    photo1: playlandPhoto1,
    photo2: playlandPhoto2,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "qr-scan",
    image: qrScanImage,
    title: "QR Scan",
    description:
      "It's an application that we coded specifically for one of my customers that works on their phone. The application allows us to extract the texts from the photos and store them in the format desired by the user and as an excel file on his phone.",
    tags: ["React Native", "SQLite", "AWS"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "https://github.com/mertcankose/qrscan",
    generalLink: "/work/qr-scan",
    photo1: qrScanPhoto1,
    photo2: qrScanPhoto2,
    text: "",
    type: "mobile",
    type2: "",
  },
  {
    name: "okko",
    image: okkoImage,
    title: "Okko",
    description:
      "Okko is an entertainment company with adventure parks and various other entertainment centers. I developed a ticket buying application for this company. The idea is that there is no queue at the box office and people can buy tickets easily.",
    tags: ["React", "Vite", "TailwindCSS", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "https://bilet.okko.com.tr/",
    githubLink: "",
    generalLink: "/work/okko",
    photo1: okkoPhoto1,
    photo2: okkoPhoto2,
    text: "",
    type: "web",
    type2: "backend",
  },
  {
    name: "e-servis",
    image: eservisImage,
    title: "E-Servis",
    description:
      "A platform where parents can monitor their children on the school bus along the way, and school management and service companies can easily control and manage the bus.",
    tags: ["React", "Vite", "TailwindCSS", "Google Map"],
    playStore: "https://play.google.com/store/apps/details?id=com.vyros.eservis&pli=1",
    appStore: "https://apps.apple.com/tr/app/eservis/id6463719378",
    webLink: "https://panel.eservis.app/",
    githubLink: "",
    generalLink: "/work/e-servis",
    photo1: eservisPhoto1,
    photo2: eservisPhoto2,
    text: "Sample Login\nphone: +905359161408\npassword: 1230,aaa",
    type: "web",
    type2: "",
  },
  {
    name: "funlord-admin",
    image: funlordWebImage,
    title: "Funlord Admin Panel",
    description:
      "Admin panel of Funlord mobile application. It's a React project that I wrote with a few developers that the staff or application owners in entertainment centers can use as super admins.",
    tags: ["React", "Vite", "TailwindCSS", "Python", "Django", "PostgreSQL"],
    playStore: "",
    appStore: "",
    webLink: "https://www.funlord.com.tr/",
    githubLink: "",
    generalLink: "/work/funlord-admin",
    photo1: funlordAdminPhoto1,
    photo2: funlordAdminPhoto2,
    text: "",
    type: "web",
    type2: "backend",
  },
  {
    name: "node-api",
    image: nodeapiImage,
    title: "Backend Service (NodeJS)",
    description:
      "An asana clone-like API project I created with Node js and Express. I created my service by following Layered Architecture.",
    tags: ["NodeJS", "Express", "MongoDB"],
    playStore: "",
    appStore: "",
    webLink: "",
    githubLink: "https://github.com/mertcankose/node-application",
    generalLink: "/work/node-api",
    photo1: nodeapiPhoto1,
    photo2: nodeapiPhoto2,
    text: "",
    type: "backend",
    type2: "",
  },
  {
    name: "useco",
    image: usecoImage,
    title: "Useco",
    description: "A landing page of an event mobile application.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://useco.net/",
    githubLink: "",
    generalLink: "/work/useco",
    photo1: usecoPhoto1,
    photo2: usecoPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "plndverse",
    image: plndverseImage,
    title: "Playland Verse",
    description: "A landing page of an playland verse brand.",
    tags: ["React", "TailwindCSS"],
    playStore: "",
    appStore: "",
    webLink: "https://www.plndverse.com/",
    githubLink: "",
    generalLink: "/work/plndverse",
    photo1: plndversePhoto1,
    photo2: plndversePhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "e-course",
    image: ecourseImage,
    title: "E-Course",
    description: "E-Course is a example dashboard of a e-learning platform.",
    tags: ["Vue", "Vuex", "Firebase"],
    playStore: "",
    appStore: "",
    webLink: "https://e-course-dashboard.vercel.app/",
    githubLink: "",
    generalLink: "/work/e-course",
    photo1: ecoursePhoto1,
    photo2: ecoursePhoto2,
    text: "Sample Login\nemail: mertcankose97@outlook.com\npassword: 123456789",
    type: "web",
    type2: "",
  },
  {
    name: "filminn",
    image: filminnImage,
    title: "Filminn",
    description: "Filminn is a landing page of a movie platform.",
    tags: ["HTML", "CSS", "Gulp.js"],
    playStore: "",
    appStore: "",
    webLink: "https://filminn.vercel.app/",
    githubLink: "",
    generalLink: "/work/filminn",
    photo1: filminnPhoto1,
    photo2: filminnPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "direct-academy",
    image: directAcademyImage,
    title: "Direct Academy",
    description: "Dental education presentation website.",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://directacademy.net/",
    githubLink: "",
    generalLink: "/work/direct-academy",
    photo1: directacademyPhoto1,
    photo2: directacademyPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "galaksi-organization",
    image: galaksiOrganizationImage,
    title: "Galaksi Organization",
    description: "An organization website that presents the organization tools.",
    tags: ["Wordpress"],
    playStore: "",
    appStore: "",
    webLink: "https://galaksiorganizasyon.com/",
    githubLink: "",
    generalLink: "/work/galaksi-organization",
    photo1: galaksiorganizasyonPhoto1,
    photo2: galaksiorganizasyonPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "monster-hunt",
    image: monsterhuntImage,
    title: "Monster Hunt",
    description: "A little game that I developed with Vue.js. This is the first app on Vue.js.",
    tags: ["JavaScript", "Vue"],
    playStore: "",
    appStore: "",
    webLink: "https://thirsty-poitras-8a4c99.netlify.app/",
    githubLink: "",
    generalLink: "/work/monster-hunt",
    photo1: monsterhuntPhoto1,
    photo2: monsterhuntPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "daily-frontend",
    image: dailyfrontendImage,
    title: "Daily Frontend",
    description: "The Project that I am coding the designs I like. I have used a lot of Scss.",
    tags: ["Css", "Scss", "Gulp.js"],
    playStore: "",
    appStore: "",
    webLink: "https://github.com/mertcankose/Daily-Frontend",
    githubLink: "https://github.com/mertcankose/Daily-Frontend",
    generalLink: "/work/daily-frontend",
    photo1: dailyfrontendPhoto1,
    photo2: dailyfrontendPhoto2,
    text: "",
    type: "web",
    type2: "",
  },
  {
    name: "simon-game",
    image: simongameImage,
    title: "Simon Game",
    description:
      "I crafted a game using JavaScript, a project that significantly bolstered my command of the language.",
    tags: ["Css", "JavaScript"],
    playStore: "",
    appStore: "",
    webLink: "https://simongamemertcan.netlify.app/",
    githubLink: "https://github.com/mertcankose/simon-game",
    generalLink: "/work/simon-game",
    photo1: simongamePhoto1,
    photo2: simongamePhoto2,
    text: "",
    type: "web",
    type2: "",
  },
];
